grade_points:
  default:
    1: 100
    2: 95
    3: 90
    4: 85
    5: 80
    6: 70
    7: 60
    8: 50
    9: 40

achievement_points:
  A: 100
  B: 96
  C: 90


attendance_penalty:
  absence: 1.0
  tardy: 0.5
  early_leave: 0.5
  etc: 0.25
